// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1676010747);
user_pref("browser.search.region", "CN");
user_pref("calendar.list.sortOrder", "120f6f41-6e53-489a-bc7c-70f54f9ebd81");
user_pref("calendar.registry.120f6f41-6e53-489a-bc7c-70f54f9ebd81.calendar-main-default", true);
user_pref("calendar.registry.120f6f41-6e53-489a-bc7c-70f54f9ebd81.calendar-main-in-composite", true);
user_pref("calendar.registry.120f6f41-6e53-489a-bc7c-70f54f9ebd81.disabled", true);
user_pref("calendar.registry.120f6f41-6e53-489a-bc7c-70f54f9ebd81.name", "Home");
user_pref("calendar.registry.120f6f41-6e53-489a-bc7c-70f54f9ebd81.type", "storage");
user_pref("calendar.registry.120f6f41-6e53-489a-bc7c-70f54f9ebd81.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "UTC");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221101185644");
user_pref("extensions.lastAppVersion", "102.4.2");
user_pref("extensions.lastPlatformVersion", "102.4.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"e37bb2fd-5453-4dce-9410-87792fc1e446\",\"google@search.mozilla.org\":\"358ded78-8be6-46e7-a392-64f01a5e9f03\",\"ddg@search.mozilla.org\":\"065f4787-aed7-4077-8962-1351c928efda\",\"amazondotcom@search.mozilla.org\":\"43b82574-16a6-45fb-afbc-c1ce39a3c514\",\"wikipedia@search.mozilla.org\":\"b5d45bac-263a-457d-a379-11f2ee5ee0c2\",\"bing@search.mozilla.org\":\"68b47a44-b302-465e-bd31-19da3150c68e\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "bc0a6e69-082f-4102-9608-a8280a95f15");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.4.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "1d940260-df72-41a7-86fc-7362ebe243bd");
user_pref("toolkit.telemetry.previousBuildID", "20221101185644");
